"""
Script de seed para popular o banco com dados de exemplo.
Execute: python scripts/seed.py
"""
import asyncio
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
os.chdir(PROJECT_ROOT)
sys.path.insert(0, str(PROJECT_ROOT))

from app.core.database import AsyncSessionLocal, create_tables
from app.services.vehicle_service import create_or_update_vehicle
from app.services.score_service import calcular_score_batch

SAMPLE_VEHICLES = [
    {
        "titulo": "Volkswagen Gol 1.0 12V",
        "marca": "Volkswagen",
        "modelo": "Gol",
        "versao": "1.0 12V MPI",
        "ano": 2019,
        "km": 52000,
        "preco": 42000,
        "cambio": "Manual",
        "combustivel": "Flex",
        "cidade": "São Paulo",
        "estado": "SP",
        "vendedor_tipo": "Pessoa Física",
        "descricao": "Gol em ótimo estado, único dono, sem batidas, manual e chave reserva. IPVA pago e licenciado.",
        "fotos": [
            "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600",
            "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/vw-gol-2019",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Chevrolet Onix 1.0 Turbo LTZ",
        "marca": "Chevrolet",
        "modelo": "Onix",
        "versao": "1.0 Turbo LTZ",
        "ano": 2022,
        "km": 18000,
        "preco": 78000,
        "cambio": "Automático",
        "combustivel": "Flex",
        "cidade": "Rio de Janeiro",
        "estado": "RJ",
        "vendedor_tipo": "Loja",
        "descricao": "Onix turbo automático, revisão em dia na concessionária, garantia de fábrica vigente, único dono. Todas as revisões realizadas na GM.",
        "fotos": [
            "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600",
            "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/onix-turbo-2022",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Toyota Corolla 2.0 XEI",
        "marca": "Toyota",
        "modelo": "Corolla",
        "versao": "2.0 XEI",
        "ano": 2021,
        "km": 35000,
        "preco": 135000,
        "cambio": "Automático",
        "combustivel": "Flex",
        "cidade": "Belo Horizonte",
        "estado": "MG",
        "vendedor_tipo": "Concessionária",
        "descricao": "Corolla XEI em excelente estado. Revisões em dia. Garantia de fábrica até 2025. Manual, chave reserva. Único dono.",
        "fotos": [
            "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=600",
            "https://images.unsplash.com/photo-1542362567-b07e54358753?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/corolla-2021",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Honda HR-V 1.8 EXL CVT",
        "marca": "Honda",
        "modelo": "HR-V",
        "versao": "1.8 EXL CVT",
        "ano": 2020,
        "km": 48000,
        "preco": 112000,
        "cambio": "CVT",
        "combustivel": "Flex",
        "cidade": "Curitiba",
        "estado": "PR",
        "vendedor_tipo": "Pessoa Física",
        "descricao": "HR-V EXL, câmbio CVT, teto solar panorâmico, revisada, sem batidas, sem funilaria. Único dono.",
        "fotos": [
            "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/hrv-2020",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Fiat Pulse 1.3 Drive",
        "marca": "Fiat",
        "modelo": "Pulse",
        "versao": "1.3 Drive",
        "ano": 2023,
        "km": 8000,
        "preco": 95000,
        "cambio": "Automático",
        "combustivel": "Flex",
        "cidade": "Porto Alegre",
        "estado": "RS",
        "vendedor_tipo": "Concessionária",
        "descricao": "Pulse drive automático, garantia de fábrica, revisado. Carro semi-novo.",
        "fotos": [
            "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/pulse-2023",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Hyundai HB20 1.0 Vision",
        "marca": "Hyundai",
        "modelo": "HB20",
        "versao": "1.0 Vision",
        "ano": 2018,
        "km": 72000,
        "preco": 36000,
        "cambio": "Manual",
        "combustivel": "Flex",
        "cidade": "Fortaleza",
        "estado": "CE",
        "vendedor_tipo": "Pessoa Física",
        "descricao": "HB20 em bom estado. IPVA pago. Sem grandes batidas.",
        "fotos": [
            "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/hb20-2018",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Jeep Renegade 1.8 Sport",
        "marca": "Jeep",
        "modelo": "Renegade",
        "versao": "1.8 Sport",
        "ano": 2020,
        "km": 55000,
        "preco": 102000,
        "cambio": "Automático",
        "combustivel": "Flex",
        "cidade": "Brasília",
        "estado": "DF",
        "vendedor_tipo": "Loja",
        "descricao": "Renegade Sport automático, revisões em dia. Carro bem conservado.",
        "fotos": [
            "https://images.unsplash.com/photo-1571987502951-3b4b62df2b17?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/renegade-2020",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Renault Kwid 1.0 Zen",
        "marca": "Renault",
        "modelo": "Kwid",
        "versao": "1.0 Zen",
        "ano": 2021,
        "km": 29000,
        "preco": 52000,
        "cambio": "Manual",
        "combustivel": "Flex",
        "cidade": "Salvador",
        "estado": "BA",
        "vendedor_tipo": "Pessoa Física",
        "descricao": "Kwid Zen 2021 em ótimo estado, único dono, manual e chave reserva. Revisões todas feitas.",
        "fotos": [
            "https://images.unsplash.com/photo-1631467862476-57c60f9e5584?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/kwid-2021",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Ford Ranger 3.2 XLT 4x4",
        "marca": "Ford",
        "modelo": "Ranger",
        "versao": "3.2 XLT 4x4",
        "ano": 2019,
        "km": 88000,
        "preco": 165000,
        "cambio": "Automático",
        "combustivel": "Diesel",
        "cidade": "Goiânia",
        "estado": "GO",
        "vendedor_tipo": "Loja",
        "descricao": "Ranger XLT Diesel 4x4 automática, revisões feitas, muito bem conservada. Caminhonete de trabalho.",
        "fotos": [
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/ranger-2019",
        "source_name": "DeepCar",
    },
    {
        "titulo": "BMW 320i 2.0 Sport ActiveFlex",
        "marca": "BMW",
        "modelo": "320i",
        "versao": "2.0 Sport ActiveFlex",
        "ano": 2020,
        "km": 42000,
        "preco": 198000,
        "cambio": "Automático",
        "combustivel": "Flex",
        "cidade": "São Paulo",
        "estado": "SP",
        "vendedor_tipo": "Concessionária",
        "descricao": "BMW 320i Sport ActiveFlex, revisões em concessionária BMW, garantia. Teto solar, bancos de couro.",
        "fotos": [
            "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/bmw320i-2020",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Nissan Kicks 1.6 SV",
        "marca": "Nissan",
        "modelo": "Kicks",
        "versao": "1.6 SV CVT",
        "ano": 2022,
        "km": 22000,
        "preco": 118000,
        "cambio": "CVT",
        "combustivel": "Flex",
        "cidade": "Recife",
        "estado": "PE",
        "vendedor_tipo": "Loja",
        "descricao": "Kicks SV CVT 2022, semi-novo, garantia de fábrica, revisada, sem detalhes.",
        "fotos": [
            "https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/kicks-2022",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Peugeot 208 1.6 Griffe",
        "marca": "Peugeot",
        "modelo": "208",
        "versao": "1.6 Griffe THP",
        "ano": 2018,
        "km": 65000,
        "preco": 59000,
        "cambio": "Automático",
        "combustivel": "Flex",
        "cidade": "Campinas",
        "estado": "SP",
        "vendedor_tipo": "Pessoa Física",
        "descricao": "208 Griffe automático turbo, revisado, sem batidas, manual do proprietário.",
        "fotos": [
            "https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/peugeot208-2018",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Volkswagen T-Cross 200 TSI Highline",
        "marca": "Volkswagen",
        "modelo": "T-Cross",
        "versao": "200 TSI Highline",
        "ano": 2023,
        "km": 5000,
        "preco": 152000,
        "cambio": "Automático",
        "combustivel": "Flex",
        "cidade": "São Paulo",
        "estado": "SP",
        "vendedor_tipo": "Concessionária",
        "descricao": "T-Cross Highline 2023, zero km, garantia de fábrica. Todos os opcionais.",
        "fotos": [
            "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/tcross-2023",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Toyota Hilux 2.8 SRX 4x4",
        "marca": "Toyota",
        "modelo": "Hilux",
        "versao": "2.8 SRX 4x4",
        "ano": 2021,
        "km": 58000,
        "preco": 285000,
        "cambio": "Automático",
        "combustivel": "Diesel",
        "cidade": "Manaus",
        "estado": "AM",
        "vendedor_tipo": "Loja",
        "descricao": "Hilux SRX automática 4x4 diesel, revisões em dia, sem grandes batidas. Muito bem conservada.",
        "fotos": [
            "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/hilux-2021",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Honda Civic 2.0 EXL CVT",
        "marca": "Honda",
        "modelo": "Civic",
        "versao": "2.0 EXL CVT",
        "ano": 2019,
        "km": 61000,
        "preco": 108000,
        "cambio": "CVT",
        "combustivel": "Flex",
        "cidade": "Florianópolis",
        "estado": "SC",
        "vendedor_tipo": "Pessoa Física",
        "descricao": "Civic EXL CVT 2019, único dono, todas revisões Honda, sem batidas, sem pintura. Manual, chave reserva.",
        "fotos": [
            "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/civic-2019",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Chevrolet Tracker 1.2 Turbo Premier",
        "marca": "Chevrolet",
        "modelo": "Tracker",
        "versao": "1.2 Turbo Premier",
        "ano": 2022,
        "km": 25000,
        "preco": 138000,
        "cambio": "Automático",
        "combustivel": "Flex",
        "cidade": "Porto Alegre",
        "estado": "RS",
        "vendedor_tipo": "Concessionária",
        "descricao": "Tracker Premier 2022, teto solar, pacote premium, garantia vigente, revisões OK.",
        "fotos": [
            "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/tracker-2022",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Fiat Strada 1.3 Endurance CD",
        "marca": "Fiat",
        "modelo": "Strada",
        "versao": "1.3 Endurance CD",
        "ano": 2022,
        "km": 38000,
        "preco": 82000,
        "cambio": "Manual",
        "combustivel": "Flex",
        "cidade": "Ribeirão Preto",
        "estado": "SP",
        "vendedor_tipo": "Pessoa Física",
        "descricao": "Strada Endurance cabine dupla, 2022, sem batidas, revisada, único dono.",
        "fotos": [
            "https://images.unsplash.com/photo-1542362567-b07e54358753?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/strada-2022",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Mercedes-Benz C180 1.6 Turbo",
        "marca": "Mercedes-Benz",
        "modelo": "C180",
        "versao": "1.6 Turbo",
        "ano": 2017,
        "km": 92000,
        "preco": 128000,
        "cambio": "Automático",
        "combustivel": "Gasolina",
        "cidade": "São Paulo",
        "estado": "SP",
        "vendedor_tipo": "Loja",
        "descricao": "C180 turbo automática 2017, revisada, bancos de couro, teto solar. Aceito troca.",
        "fotos": [
            "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/c180-2017",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Volkswagen Polo 1.0 200 TSI Comfortline",
        "marca": "Volkswagen",
        "modelo": "Polo",
        "versao": "1.0 200 TSI Comfortline",
        "ano": 2021,
        "km": 31000,
        "preco": 88000,
        "cambio": "Automático",
        "combustivel": "Flex",
        "cidade": "Belo Horizonte",
        "estado": "MG",
        "vendedor_tipo": "Pessoa Física",
        "descricao": "Polo TSI automático 2021, único dono, revisões Volkswagen, sem batidas, sem pintura.",
        "fotos": [
            "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/polo-2021",
        "source_name": "DeepCar",
    },
    {
        "titulo": "Mitsubishi Outlander 3.0 V6 GT 4WD",
        "marca": "Mitsubishi",
        "modelo": "Outlander",
        "versao": "3.0 V6 GT 4WD",
        "ano": 2019,
        "km": 75000,
        "preco": 175000,
        "cambio": "Automático",
        "combustivel": "Gasolina",
        "cidade": "Curitiba",
        "estado": "PR",
        "vendedor_tipo": "Loja",
        "descricao": "Outlander GT V6 4WD, revisado, 7 lugares, teto solar panorâmico, couro.",
        "fotos": [
            "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600",
        ],
        "source_url": "https://deepcar.com.br/seed/outlander-2019",
        "source_name": "DeepCar",
    },
]


async def seed():
    print("Creating tables...")
    await create_tables()

    print("Calculating scores...")
    scored = calcular_score_batch(SAMPLE_VEHICLES, calcular_media_por_modelo=True)

    print(f"Inserting {len(scored)} vehicles...")
    async with AsyncSessionLocal() as db:
        for vehicle_data in scored:
            try:
                vehicle = await create_or_update_vehicle(db, vehicle_data)
                print(f"  Saved: {vehicle.titulo} (score: {vehicle.score})")
            except Exception as e:
                print(f"  Error saving {vehicle_data.get('titulo', 'unknown')}: {e}")

    print("Seed completed!")


if __name__ == "__main__":
    asyncio.run(seed())
